// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzVs0ggeiXzdDZDPL2hkuUuo6yGOtS9i0',
    appId: '1:767150725312:web:c1ce0c8186f58f3d703525',
    messagingSenderId: '767150725312',
    projectId: 'kith-and-kin-123',
    authDomain: 'kith-and-kin-123.firebaseapp.com',
    storageBucket: 'kith-and-kin-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETRLtI-PrlkMHeRTBTXJcvQ6jOaB-KzY',
    appId: '1:767150725312:android:5be2714f7954703d703525',
    messagingSenderId: '767150725312',
    projectId: 'kith-and-kin-123',
    storageBucket: 'kith-and-kin-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPTYjrXH9Wg9klAuQDUKJ2f1Hm1hbIVeM',
    appId: '1:767150725312:ios:de63dae30ffcad84703525',
    messagingSenderId: '767150725312',
    projectId: 'kith-and-kin-123',
    storageBucket: 'kith-and-kin-123.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProjectKintkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPTYjrXH9Wg9klAuQDUKJ2f1Hm1hbIVeM',
    appId: '1:767150725312:ios:de63dae30ffcad84703525',
    messagingSenderId: '767150725312',
    projectId: 'kith-and-kin-123',
    storageBucket: 'kith-and-kin-123.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProjectKintkin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzVs0ggeiXzdDZDPL2hkuUuo6yGOtS9i0',
    appId: '1:767150725312:web:aa1139016079d94f703525',
    messagingSenderId: '767150725312',
    projectId: 'kith-and-kin-123',
    authDomain: 'kith-and-kin-123.firebaseapp.com',
    storageBucket: 'kith-and-kin-123.firebasestorage.app',
  );
}
